#!/bin/bash

# Copyright 2013, Intel Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

error() { echo "git-cclone ERROR: $*" >&2; exit 1; }
info() { echo "git-clone $*" >&2; }

[[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf

[[ -z "$GIT_CACHE_SERVER" ]] && error "variable GIT_CACHE_SERVER undefined"

repo="$1"
dir="${2:-$(basename $repo .git)}"
mirror=$3 # optional --mirror (used by git-crecover) or --bare (can be set by user)

[[ -d "$dir" ]] && error "directory $dir exists"

info "asking $GIT_CACHE_SERVER a cache for $repo"
cpath=$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo") || error "server failure"
[[ -z "$cpath" ]] && error "can't get a cache"
crepo="${GIT_CACHE_SERVER}:${cpath}"

info "Upstream repository: $repo"
info "Cache repository: $crepo"

git clone $mirror "$crepo" "$dir" >&2 || error "failure of git clone $mirror $crepo $dir"

cd "$dir" || error "can't go to directory $dir"

git remote set-url --push origin "$repo" >&2
git config remote.origin.uploadpack gitcache-server >&2
info "done. Git-cache is active for future fetch operations"

