#!/bin/bash

error() { echo "ERROR(git-cache-clone): $*" >&2; exit 1; }
info() { echo "INFO(git-cache-clone): $*" >&2; }

[[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf

[[ -z "$GIT_CACHE_SERVER" ]] && error "variable GIT_CACHE_SERVER undefined"

repo="$1"
dir="${2:-$(basename $repo .git)}"
mirror=$3 # option --mirror

[[ -d "$dir" ]] && error "directory $dir exists"

info "asking $GIT_CACHE_SERVER a cache for $repo"
crepo=$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo")
[[ -z "$crepo" ]] && error "can't get a cache"

info "cache for $repo is $crepo"

info "cloning $crepo into $dir"
git clone $mirror "$crepo" "$dir"

info "init of git $dir"
cd "$dir"
git remote set-url --push origin "$repo"
git config remote.origin.uploadpack gitcache-server
info "done"

