#!/bin/bash

# Copyright 2013, Intel Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# prefix log with cache server name
log() {
	srvid="git-cclone"
	while IFS='' read -r line; do 
		echo "$srvid $line" >&2
	done
}
exec 2> >(log)

error() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "INFO: $*" >&2; }

[[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf

[[ -z "$GIT_CACHE_SERVER" ]] && error "variable GIT_CACHE_SERVER undefined"

repo="$1"
dir="${2:-$(basename $repo .git)}"
mirror=$3 # optional --mirror (used by git-crecover) or --bare (can be set by user)

[[ -d "$dir" ]] && error "directory $dir exists"

info "asking $GIT_CACHE_SERVER a cache for $repo"
crepo="${GIT_CACHE_SERVER}:$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo")"
[[ -z "$crepo" ]] && error "can't get a cache"

info "Upstream repository: $repo"
info "Cache repository: $crepo"
info "Cloning to local directory: $dir"

git clone $mirror "$crepo" "$dir" >&2

cd "$dir"
git remote set-url --push origin "$repo" >&2
git config remote.origin.uploadpack gitcache-server >&2
info "done: cache server will be used for fetch operations"

