#!/bin/bash

# Copyright 2013, Intel Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# prefix log with cache server name
log() {
	srvid="git-crecover"
	while IFS='' read -r line; do 
		echo "$srvid $line" >&2
	done
}
exec 2> >(log)

error() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "INFO: $*" >&2; }

[[ -r ~/.gitcache.conf ]] && . ~/.gitcache.conf

repo="$(git remote -v | awk '$1=="origin" && $3=="(push)"{print $2}')"

do_recover() {
    info "recovering cache for $repo"
    [[ -z "$GIT_CACHE_SERVER" ]] && error "variable GIT_CACHE_SERVER undefined"
    info "asking $GIT_CACHE_SERVER a cache for $repo"
    crepo="${GIT_CACHE_SERVER}:$(ssh "$GIT_CACHE_SERVER" gitcache-server --clone "$repo")"
    [[ -z "$crepo" ]] && error "can't get a cache"
    info "init of git $dir"
    git remote set-url origin "$crepo" >&2
    git remote set-url --push origin "$repo" >&2
    git config remote.origin.uploadpack gitcache-server >&2
    info "done"
    exit 0
}

do_remove() {
    info "removing cache reference"
    git config --unset remote.origin.uploadpack >&2
    git remote set-url origin "$repo" >&2
    info "done"
    exit 0
}

case "$1" in
    -a|--auto) do_recover;;
    -r|--remove) do_remove;;
esac

cat << EOC

You have two ways of recovering from a cache miss of git-cache.
You can either REMOVE the caching indirection or you can RECOVER
the cache and reset it to the current directory.

EOC
PS3="What to do? "
select action in REMOVE RECOVER; do
    case $action in
	REMOVE) do_remove;;
	RECOVER) do_recover;;
    esac
done

